#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
reskill v1.2.0 — GitHub Skill 发布/更新一站式
用途：把 GitHub 仓库按 Agent Skills 规范完整发布出来：
      1. 验证仓库根 SKILL.md 合规
      2. 加 agent-skills topic
      3. 创建 GitHub release（带 semver tag）
      4. 写发布快照
注意：gh skill publish 严格要求 `skills/<name>/SKILL.md` 结构
      （name 必须等于目录名），仓库根 SKILL.md 会验证失败。
      本脚本不依赖 gh skill publish，直接调 GitHub API 完成等价动作，
      适用于仓库根 SKILL.md 结构。
用法:
  python3 gh_release.py REPO --tag vX.Y.Z [--dry-run] [--skip-validate]
  python3 gh_release.py totwo2/reskill --tag v1.2.0 --dry-run
"""
import argparse, subprocess, sys, os, json, datetime, re

def run(cmd, cwd=None, check=True, capture=True):
    """subprocess wrapper"""
    print(f"$ {' '.join(cmd) if isinstance(cmd, list) else cmd}")
    r = subprocess.run(cmd, cwd=cwd, shell=isinstance(cmd, str),
                       capture_output=capture, text=True)
    if check and r.returncode != 0:
        sys.stderr.write(f"❌ exit {r.returncode}\n{r.stderr}\n")
        sys.exit(r.returncode)
    return r

def parse_owner_repo(s):
    if "/" not in s:
        sys.exit("❌ REPO 必须是 owner/name 格式")
    o, n = s.split("/", 1)
    return o, n

def get_skill_md(owner, repo):
    """拉仓库根 SKILL.md"""
    r = run(["gh", "api", f"repos/{owner}/{repo}/contents/SKILL.md"])
    if r.returncode != 0:
        return None, None
    import base64
    content = base64.b64decode(json.loads(r.stdout)["content"]).decode("utf-8")
    sha = json.loads(r.stdout)["sha"]
    return content, sha

def parse_frontmatter(skill_md):
    """提取 YAML frontmatter"""
    m = re.match(r"^---\n(.*?)\n---", skill_md, re.DOTALL)
    if not m:
        return {}
    fm = {}
    cur_key = None
    for line in m.group(1).splitlines():
        if line.startswith("  ") and cur_key:
            # 续行
            fm[cur_key] += "\n" + line.strip()
        elif ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
            cur_key = k.strip()
    return fm

def validate(skill_md, repo_name):
    """严格按 agentskills.io 规范校验"""
    fm = parse_frontmatter(skill_md)
    errors = []
    warnings = []

    name = fm.get("name", "")
    # 命名规则：1-64 字符，仅小写字母数字连字符，不首尾连字符，不连续连字符
    if not name:
        errors.append("frontmatter 缺 name")
    elif not re.match(r"^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$", name):
        errors.append(f"name '{name}' 不符合命名规则（仅小写字母数字连字符，1-64字符，不首尾/连续连字符）")
    if name != repo_name:
        errors.append(f"name '{name}' 必须等于仓库名 '{repo_name}'")

    desc = fm.get("description", "")
    if not desc:
        errors.append("frontmatter 缺 description")
    elif len(desc) > 1024:
        warnings.append(f"description 长度 {len(desc)} 超过 1024 字符")

    allowed_tools = fm.get("allowed-tools")
    if allowed_tools and allowed_tools.startswith("["):
        errors.append("allowed-tools 必须是字符串不是数组（gh skill 规范）")

    body_match = re.search(r"^---\n.*?\n---\n(.*)", skill_md, re.DOTALL)
    if body_match and len(body_match.group(1).splitlines()) > 500:
        warnings.append(f"SKILL.md 正文超过 500 行（推荐上限）")

    if not fm.get("license"):
        warnings.append("推荐加 license 字段")

    return errors, warnings

def ensure_topic(owner, repo, topic="agent-skills"):
    """加 topic"""
    cur = run(["gh", "api", f"repos/{owner}/{repo}/topics"])
    topics = json.loads(cur.stdout).get("names", [])
    if topic in topics:
        print(f"   ✅ topic '{topic}' 已存在")
        return
    run(["gh", "repo", "edit", f"{owner}/{repo}", "--add-topic", topic])
    print(f"   ✅ 已加 topic '{topic}'")

def create_release(owner, repo, tag, dry_run=False):
    """创建 GitHub release"""
    r = subprocess.run(["gh", "release", "view", tag, "--repo", f"{owner}/{repo}"],
                       capture_output=True, text=True)
    if r.returncode == 0:
        print(f"   ⚠️  release {tag} 已存在，跳过创建")
        return

    notes = (f"Skill release {tag}\n\n"
             f"- Auto-generated by reskill gh_release.py\n"
             f"- Time: {datetime.datetime.now():%Y-%m-%d %H:%M:%S}\n"
             f"- Validated against Agent Skills specification v1.0.0")

    cmd = ["gh", "release", "create", tag, "--repo", f"{owner}/{repo}",
           "--title", f"{repo} {tag}", "--notes", notes]
    if dry_run:
        # dry-run 跳过实际创建，仅打印命令
        print(f"   [dry-run] 跳过创建 release")
        print(f"   计划命令: {' '.join(cmd)}")
        return
    run(cmd)
    print(f"   ✅ release {tag} 已创建")

def write_snapshot(owner, repo, tag, validation, dry_run):
    """写发布快照"""
    HERE = os.path.dirname(os.path.abspath(__file__))
    SETTINGS = os.path.join(os.path.dirname(HERE), "settings")
    SNAPSHOT_DIR = os.path.join(SETTINGS, "release_history")
    os.makedirs(SNAPSHOT_DIR, exist_ok=True)
    fp = os.path.join(SNAPSHOT_DIR, f"{repo}.yaml")

    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    entry = (f"\n- time: \"{ts}\"\n"
             f"  repo: {owner}/{repo}\n"
             f"  tag: {tag}\n"
             f"  dry_run: {dry_run}\n"
             f"  errors: {len(validation[0])}\n"
             f"  warnings: {len(validation[1])}\n")

    if not os.path.exists(fp):
        with open(fp, "w", encoding="utf-8") as f:
            f.write(f"# {owner}/{repo} release 历史\n\nreleases:\n{entry}")
    else:
        with open(fp, "a", encoding="utf-8") as f:
            f.write(entry)
    print(f"   ✅ 快照写入 {fp}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("repo", help="owner/name")
    ap.add_argument("--tag", required=True, help="版本 tag，如 v1.2.0")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--skip-validate", action="store_true",
                    help="跳过本地 frontmatter 校验（不推荐）")
    ap.add_argument("--skip-secret-scan", action="store_true",
                    help="跳过凭据扫描（不推荐）")
    args = ap.parse_args()

    owner, repo = parse_owner_repo(args.repo)
    print(f"🚀 GitHub Skill 发布 — {owner}/{repo} @ {args.tag}\n")

    # 1. 拉 SKILL.md
    print("📥 拉取 SKILL.md...")
    skill_md, sha = get_skill_md(owner, repo)
    if not skill_md:
        sys.exit("❌ 仓库根无 SKILL.md")

    # 2. 校验
    if not args.skip_validate:
        print("🔍 校验 SKILL.md...")
        errors, warnings = validate(skill_md, repo)
        if errors:
            for e in errors: print(f"   ❌ {e}")
            sys.exit("❌ 校验未通过，修复后再发布")
        for w in warnings: print(f"   ⚠️  {w}")
        if not errors and not warnings:
            print("   ✅ 校验通过")
    else:
        errors, warnings = [], []

    # 3. （gh skill publish 不适用：需 skills/<name>/ 结构，本仓库为根 SKILL.md）
    print("⏩ 跳过 gh skill publish（仓库根 SKILL.md 结构不符要求）")

    # 4. 加 topic
    if not args.dry_run:
        print("\n🏷️  添加 topic...")
        ensure_topic(owner, repo)

    # 5. 创建 release
    print(f"\n🚀 创建 release {args.tag}...")
    create_release(owner, repo, args.tag, dry_run=args.dry_run)

    # 6. 写快照
    write_snapshot(owner, repo, args.tag, (errors, warnings), args.dry_run)

    # 7. 验证索引
    print("\n🔎 验证 skill 可被发现...")
    r = run(["gh", "skill", "search", repo], check=False)
    if repo in r.stdout:
        print(f"   ✅ '{repo}' 出现在 gh skill search 结果中")
    else:
        print(f"   ⚠️  '{repo}' 暂时没被索引（release 创建后需要几分钟生效）")

    print(f"\n✅ 完成 — {owner}/{repo} @ {args.tag}")

if __name__ == "__main__":
    main()